project_name: kubectl-unused-volumes
release:
  github:
    owner: dirathea
    name: kubectl-unused-volumes
builds:
  - id: kubectl-unused-volumes
    binary: unused-volumes
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/dirathea/kubectl-unused-volumes/pkg/version.version=
archives:
  - id: kubectl-unused-volumes
    builds:
    - kubectl-unused-volumes
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256