project_name: kubectl-volume-reclaim
release:
  github:
    owner: dirathea
    name: kubectl-volume-reclaim
builds:
  - id: kubectl-volume-reclaim
    binary: volume-reclaim
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/dirathea/kubectl-volume-reclaim/pkg/version.version=
archives:
  - id: kubectl-volume-reclaim
    builds:
    - kubectl-volume-reclaim
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256